/**
 * The 99 Names of Allah (أسماء الله الحسنى) — Arabic name, transliteration,
 * and an English meaning gloss. Static reference content, not user data.
 */
export interface AsmaName {
  /** 1-based position in the traditional list. */
  number: number;
  ar: string;
  transliteration: string;
  en: string;
}

/**
 * Strips Arabic diacritics (tashkeel) and tatweel so a plain search like
 * "نور" matches a fully-vocalized stored name like "النُّور" — without this,
 * the diacritic characters sit between letters and break the substring
 * match entirely.
 */
export function stripTashkeel(s: string): string {
  return s.replace(/[ً-ْٰـ]/g, "");
}

export const ASMA_AL_HUSNA: AsmaName[] = [
  { number: 1, ar: "الرَّحْمَن", transliteration: "Ar-Rahman", en: "The Most Compassionate" },
  { number: 2, ar: "الرَّحِيم", transliteration: "Ar-Raheem", en: "The Most Merciful" },
  { number: 3, ar: "الْمَلِك", transliteration: "Al-Malik", en: "The King, The Sovereign" },
  { number: 4, ar: "الْقُدُّوس", transliteration: "Al-Quddus", en: "The Most Sacred" },
  { number: 5, ar: "السَّلاَم", transliteration: "As-Salam", en: "The Source of Peace" },
  { number: 6, ar: "الْمُؤْمِن", transliteration: "Al-Mu'min", en: "The Giver of Faith and Security" },
  { number: 7, ar: "الْمُهَيْمِن", transliteration: "Al-Muhaymin", en: "The Guardian, The Protector" },
  { number: 8, ar: "الْعَزِيز", transliteration: "Al-Aziz", en: "The Almighty, The Honorable" },
  { number: 9, ar: "الْجَبَّار", transliteration: "Al-Jabbar", en: "The Compeller, The Restorer" },
  { number: 10, ar: "الْمُتَكَبِّر", transliteration: "Al-Mutakabbir", en: "The Supreme, The Majestic" },
  { number: 11, ar: "الْخَالِق", transliteration: "Al-Khaliq", en: "The Creator" },
  { number: 12, ar: "الْبَارِئ", transliteration: "Al-Bari'", en: "The Evolver, The Maker" },
  { number: 13, ar: "الْمُصَوِّر", transliteration: "Al-Musawwir", en: "The Fashioner, The Shaper" },
  { number: 14, ar: "الْغَفَّار", transliteration: "Al-Ghaffar", en: "The Ever-Forgiving" },
  { number: 15, ar: "الْقَهَّار", transliteration: "Al-Qahhar", en: "The Subduer, The Dominant" },
  { number: 16, ar: "الْوَهَّاب", transliteration: "Al-Wahhab", en: "The Bestower" },
  { number: 17, ar: "الرَّزَّاق", transliteration: "Ar-Razzaq", en: "The Provider, The Sustainer" },
  { number: 18, ar: "الْفَتَّاح", transliteration: "Al-Fattah", en: "The Opener, The Judge" },
  { number: 19, ar: "اَلْعَلِيْم", transliteration: "Al-Alim", en: "The All-Knowing" },
  { number: 20, ar: "الْقَابِض", transliteration: "Al-Qabid", en: "The Restrainer, The Withholder" },
  { number: 21, ar: "الْبَاسِط", transliteration: "Al-Basit", en: "The Extender, The Expander" },
  { number: 22, ar: "الْخَافِض", transliteration: "Al-Khafid", en: "The Abaser" },
  { number: 23, ar: "الرَّافِع", transliteration: "Ar-Rafi'", en: "The Exalter" },
  { number: 24, ar: "الْمُعِزّ", transliteration: "Al-Mu'izz", en: "The Bestower of Honor" },
  { number: 25, ar: "المُذِلّ", transliteration: "Al-Mudhill", en: "The Humiliator" },
  { number: 26, ar: "السَّمِيع", transliteration: "As-Sami", en: "The All-Hearing" },
  { number: 27, ar: "الْبَصِير", transliteration: "Al-Basir", en: "The All-Seeing" },
  { number: 28, ar: "الْحَكَم", transliteration: "Al-Hakam", en: "The Judge, The Arbitrator" },
  { number: 29, ar: "الْعَدْل", transliteration: "Al-'Adl", en: "The Utterly Just" },
  { number: 30, ar: "اللَّطِيف", transliteration: "Al-Latif", en: "The Subtle, The Most Gentle" },
  { number: 31, ar: "الْخَبِير", transliteration: "Al-Khabir", en: "The All-Aware" },
  { number: 32, ar: "الْحَلِيم", transliteration: "Al-Halim", en: "The Forbearing, The Indulgent" },
  { number: 33, ar: "الْعَظِيم", transliteration: "Al-Azim", en: "The Magnificent, The Supreme" },
  { number: 34, ar: "الْغَفُور", transliteration: "Al-Ghafur", en: "The Great Forgiver" },
  { number: 35, ar: "الشَّكُور", transliteration: "Ash-Shakur", en: "The Most Appreciative" },
  { number: 36, ar: "الْعَلِيّ", transliteration: "Al-Ali", en: "The Most High" },
  { number: 37, ar: "الْكَبِير", transliteration: "Al-Kabir", en: "The Most Great" },
  { number: 38, ar: "الْحَفِيظ", transliteration: "Al-Hafiz", en: "The Preserver, The Protector" },
  { number: 39, ar: "المُقيت", transliteration: "Al-Muqit", en: "The Sustainer, The Nourisher" },
  { number: 40, ar: "الْحسِيب", transliteration: "Al-Hasib", en: "The Reckoner" },
  { number: 41, ar: "الْجَلِيل", transliteration: "Al-Jalil", en: "The Majestic" },
  { number: 42, ar: "الْكَرِيم", transliteration: "Al-Karim", en: "The Most Generous, The Bountiful" },
  { number: 43, ar: "الرَّقِيب", transliteration: "Ar-Raqib", en: "The Watchful" },
  { number: 44, ar: "الْمُجِيب", transliteration: "Al-Mujib", en: "The Responsive, The Answerer" },
  { number: 45, ar: "الْوَاسِع", transliteration: "Al-Wasi'", en: "The All-Encompassing, The Boundless" },
  { number: 46, ar: "الْحَكِيم", transliteration: "Al-Hakim", en: "The All-Wise" },
  { number: 47, ar: "الْوَدُود", transliteration: "Al-Wadud", en: "The Most Loving" },
  { number: 48, ar: "الْمَجِيد", transliteration: "Al-Majid", en: "The Most Glorious" },
  { number: 49, ar: "الْبَاعِث", transliteration: "Al-Ba'ith", en: "The Resurrector" },
  { number: 50, ar: "الشَّهِيد", transliteration: "Ash-Shahid", en: "The Witness" },
  { number: 51, ar: "الْحَقّ", transliteration: "Al-Haqq", en: "The Absolute Truth" },
  { number: 52, ar: "الْوَكِيل", transliteration: "Al-Wakil", en: "The Trustee, The Disposer of Affairs" },
  { number: 53, ar: "الْقَوِيّ", transliteration: "Al-Qawiyy", en: "The All-Strong" },
  { number: 54, ar: "الْمَتِين", transliteration: "Al-Matin", en: "The Firm, The Steadfast" },
  { number: 55, ar: "الْوَلِيّ", transliteration: "Al-Waliyy", en: "The Protecting Friend" },
  { number: 56, ar: "الْحَمِيد", transliteration: "Al-Hamid", en: "The Praiseworthy" },
  { number: 57, ar: "الْمُحْصِي", transliteration: "Al-Muhsi", en: "The Reckoner, The Counter" },
  { number: 58, ar: "الْمُبْدِئ", transliteration: "Al-Mubdi'", en: "The Originator" },
  { number: 59, ar: "الْمُعِيد", transliteration: "Al-Mu'id", en: "The Restorer, The Reinstater" },
  { number: 60, ar: "يُحيي", transliteration: "Al-Muhyi", en: "The Giver of Life" },
  { number: 61, ar: "يُمِيت", transliteration: "Al-Mumit", en: "The Bringer of Death" },
  { number: 62, ar: "الْحَيّ", transliteration: "Al-Hayy", en: "The Ever-Living" },
  { number: 63, ar: "الْقَيُّوم", transliteration: "Al-Qayyum", en: "The Self-Subsisting, Sustainer of All" },
  { number: 64, ar: "الْوَاجِد", transliteration: "Al-Wajid", en: "The Perceiver, The Finder" },
  { number: 65, ar: "الْمَاجِد", transliteration: "Al-Majid", en: "The Illustrious, The Magnificent" },
  { number: 66, ar: "الْواحِد", transliteration: "Al-Wahid", en: "The One" },
  { number: 67, ar: "اَلاَحَد", transliteration: "Al-Ahad", en: "The Unique, The Only One" },
  { number: 68, ar: "الصَّمَد", transliteration: "As-Samad", en: "The Eternal, The Self-Sufficient" },
  { number: 69, ar: "الْقَادِر", transliteration: "Al-Qadir", en: "The All-Powerful" },
  { number: 70, ar: "الْمُقْتَدِر", transliteration: "Al-Muqtadir", en: "The Determiner, The Powerful" },
  { number: 71, ar: "الْمُقَدِّم", transliteration: "Al-Muqaddim", en: "The Expediter, The Promoter" },
  { number: 72, ar: "الْمُؤَخِّر", transliteration: "Al-Mu'akhkhir", en: "The Delayer, The Postponer" },
  { number: 73, ar: "الأوَّل", transliteration: "Al-Awwal", en: "The First" },
  { number: 74, ar: "الآخِر", transliteration: "Al-Akhir", en: "The Last" },
  { number: 75, ar: "الظَّاهِر", transliteration: "Az-Zahir", en: "The Manifest, The Evident" },
  { number: 76, ar: "الْبَاطِن", transliteration: "Al-Batin", en: "The Hidden, The Unmanifest" },
  { number: 77, ar: "الْوَالِي", transliteration: "Al-Wali", en: "The Governor, The Protecting Friend" },
  { number: 78, ar: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", en: "The Most Exalted" },
  { number: 79, ar: "الْبَرّ", transliteration: "Al-Barr", en: "The Source of All Goodness" },
  { number: 80, ar: "التَّوَّاب", transliteration: "At-Tawwab", en: "The Ever-Accepting of Repentance" },
  { number: 81, ar: "الْمُنْتَقِم", transliteration: "Al-Muntaqim", en: "The Avenger" },
  { number: 82, ar: "العَفُوّ", transliteration: "Al-Afuww", en: "The Pardoner, The Effacer of Sins" },
  { number: 83, ar: "الرَّؤُوف", transliteration: "Ar-Ra'uf", en: "The Compassionate, The All-Pitying" },
  { number: 84, ar: "مَالِكُ الْمُلْك", transliteration: "Malik-ul-Mulk", en: "Owner of All Sovereignty" },
  { number: 85, ar: "ذُوالْجَلاَلِ وَالإكْرَام", transliteration: "Dhul-Jalali wal-Ikram", en: "Lord of Majesty and Generosity" },
  { number: 86, ar: "الْمُقْسِط", transliteration: "Al-Muqsit", en: "The Equitable, The Requiter" },
  { number: 87, ar: "الْجَامِع", transliteration: "Al-Jami'", en: "The Gatherer, The Uniter" },
  { number: 88, ar: "الْغَنِيّ", transliteration: "Al-Ghani", en: "The Self-Sufficient, The Wealthy" },
  { number: 89, ar: "الْمُغْنِي", transliteration: "Al-Mughni", en: "The Enricher, The Emancipator" },
  { number: 90, ar: "الْمَانِع", transliteration: "Al-Mani'", en: "The Preventer, The Withholder" },
  { number: 91, ar: "الضَّار", transliteration: "Ad-Darr", en: "The Distresser, The Afflicter" },
  { number: 92, ar: "النَّافِع", transliteration: "An-Nafi'", en: "The Propitious, The Benefactor" },
  { number: 93, ar: "النُّور", transliteration: "An-Nur", en: "The Light" },
  { number: 94, ar: "الْهَادِي", transliteration: "Al-Hadi", en: "The Guide" },
  { number: 95, ar: "الْبَدِيع", transliteration: "Al-Badi'", en: "The Incomparable Originator" },
  { number: 96, ar: "اَلْبَاقِي", transliteration: "Al-Baqi", en: "The Everlasting" },
  { number: 97, ar: "الْوَارِث", transliteration: "Al-Warith", en: "The Ultimate Inheritor" },
  { number: 98, ar: "الرَّشِيد", transliteration: "Ar-Rashid", en: "The Righteous Guide" },
  { number: 99, ar: "الصَّبُور", transliteration: "As-Sabur", en: "The Most Patient" },
];
